### ISSUE TITLE
latitude is way off

### ISSUE THREAD

**Issue by maral** [arodax/jtsk2wgs84#1]
Latitude seems to be okay, but longitude is off by almost a kilometer in my example.

input: 1167938.93, 515366.32
expected output: 49.20526945954302, 17.748366340656077
output: 49.20526887569716, 17.761517288122015

[original position (in JTSK) visualised](https://mapy.cz/zakladni?q=1167938.93%2C%20515366.32&x=17.7549630&y=49.2036364&z=16&base=ophoto)
[output position visualised](https://mapy.cz/zakladni?q=49.20526887569716%2C%2017.761517288122015&source=coor&id=17.761517288122015%2C49.20526887569716&ds=1&x=17.7565069&y=49.2050691&z=16&base=ophoto)
[difference visualized on the map](https://mapy.cz/zakladni?mereni-vzdalenosti&rm=9oaTQxTwCw3gnNR&x=17.7549630&y=49.2036364&z=16&base=ophoto)

I guess you changed the copy-pasted algorithm a bit too much?

**Comment by cur53se** [comment]
Fixed in https://github.com/arodax/jtsk2wgs84/pull/2
